### ISSUE TITLE
Investigate the effort of building iOS and Android app using stelace backend

### ISSUE THREAD

**Issue by thihamin** [justinschuldt/syr-marketplace#17]
so that we get some idea. 

Options:
1) use existing Vue.js frontend and put into iOS and Android shells.  See what still need to add or update in this case.
2) write native iOS (and Android) app.

**Comment by justinschuldt** [comment]
Can use this https://quasar.dev/quasar-cli/developing-mobile-apps

**Comment by justinschuldt** [comment]
Hybrid mobile app with the existing frontend would work for iOS and Android.

**Comment by sittingbull15** [comment]
Let's go Hybrid https://www.mobiloud.com/blog/native-web-or-hybrid-apps#6

**Comment by justinschuldt** [comment]
I agree, one codebase shared across web/iOS/Android is the best move for a small time.

**Comment by justinschuldt** [comment]
To be clear, that link I posted in my first comment shows how to take our existing platform and wrap it into a hybrid mobile app via Capacitor.  We should definitely use that.

**Comment by sittingbull15** [comment]
Sound good. @thihamin feel free to use Oak as Dev Ops- infra (I have already talked with him) for both @justinschuldt 's side of webapp and your side of mobile initiatives.

**Comment by justinschuldt** [comment]
I am closing this as there is no clear deliverable from the discussion in this thread.
We can make specific tasks that are actionable when we know the direction we will go and ready to begin work.
