### ISSUE TITLE
Login doesn't work some time

### ISSUE THREAD

**Issue by thihamin** [justinschuldt/syr-marketplace#18]

**Comment by oslatt** [comment]
Not sometimes, it's not working for me. Only worked for the very first sign in using Google. I logged out after testing meal creation etc. and when tried to log in again and it doesn't work anymore. Cleared browser cache and tried to log in again but doesn't work. Tried typing in email and password manually and still doesn't let me log in. Not just log in, the Sign Up option after you press "Don't have an account" at log in doesn't work fully either. It creates a new account with the provided email but doesn't log you in.

**Comment by oslatt** [comment]
Log In with Facebook doesn't work as well.
![Screenshot - 486](https://user-images.githubusercontent.com/25869666/114290784-9bab9180-9a47-11eb-848d-9ae51d05a95c.png)

**Comment by justinschuldt** [comment]
This is related to redis failover behavior, I am picking this up now.

**Comment by justinschuldt** [comment]
I just fixed this by fixing a data persistence issue with redis. The cause of this was redis data not persisting through pod restarts.

Note, SSO requires a whitelist because we have not submitted our app for approval. You are seeing that message Oak because you are not whitelisted for the FB app.
