### ISSUE TITLE
"Stripe account not-linked" warning shows all the time

### ISSUE THREAD

**Issue by justinschuldt** [justinschuldt/syr-marketplace#25]
The new header notification is overzealous and appears to show all the time for users that have listed meals. Need to tweak the logic [here](https://github.com/justinschuldt/syr-marketplace/blob/dev/src/layouts/MainLayoutHeader.vue#L100).

Should only show the header notification if the user has assets, and has not linked their stripe account.

![syr-stripe-needed-noty-error](https://user-images.githubusercontent.com/2636098/114346060-6b87ef80-9b28-11eb-967c-57977063436a.PNG)

**Comment by sittingbull15** [comment]
I linked my account but the error was showing and I could not click to activate my listing.
![Stripe acct error](https://user-images.githubusercontent.com/10750234/114809156-aaf84b00-9d77-11eb-8995-1c4ad0de0b52.JPG)

**Comment by sittingbull15** [comment]
Need to be able to include a Free option to checkout without Stripe, some posts may not be not for sale yet - teaser etc so have to think about these too. Some chefs want to give free food samples or gifts to gain buyers or drive traffics to their new menu items.

**Comment by sittingbull15** [comment]
Some folks just wanna give away free food. 
![foodshare](https://user-images.githubusercontent.com/10750234/115076393-7fd24080-9eca-11eb-8c08-0f569813e396.JPG)
