### ISSUE TITLE
Cannot enter $15.99 as a value in the price of the item

### ISSUE THREAD

**Issue by thihamin** [justinschuldt/syr-marketplace#7]
Currently, only whole numbers such as $15 are allowed.  Investigate why that is the case and what we should do to allow decimals. 

Note that the currency values should be stored using either 'decimal' type or 'integer' type.  We shouldn't use float to store currency value as the calculation using float won't be accurate because of hardware limitation.

**Comment by Digital4design** [comment]
@thihamin , this issue comes during publish your add or at other page? please confirm this
please check the screenshot : 
![image](https://user-images.githubusercontent.com/26590657/113983570-ac9dac80-9867-11eb-8819-fef064a44935.png)

**Comment by thihamin** [comment]
@Digital4design i think I saw the issue when I was adding a new item to sell. Can you reproduce the issue?

**Comment by thihamin** [comment]
> @thihamin , this issue comes during publish your add or at other page? please confirm this
> please check the screenshot :
> ![image](https://user-images.githubusercontent.com/26590657/113983570-ac9dac80-9867-11eb-8819-fef064a44935.png)

yes, that was the screenshot that i saw
